### ISSUE TITLE
Doesn't work on windows+git bash

### ISSUE THREAD

**Issue by siada** [stavshamir/bag#1]
When running on git bash, you get a FileNotFoundException:
```
Exception in thread "main" java.io.FileNotFoundException: \d\Temp\bag\aliases (The system cannot find the path specified)
```

The application.properties has been correctly created with forward slashes `alias-user-file=/d/Temp/bag/aliases` but this doesn't appear to get translated over correctly when reading the properties file.

**Comment by stavshamir** [comment]
Java File class tries to be nice and automatically converts a given path to the relevant OS, but it does so not so well for git bash.
The solution is simply to change the paths in the application.properties to a classical Windows file path, with double backslashes - in your case:
D:\\Temp\\bag\\aliases

**Comment by stavshamir** [comment]
This is a problem with the conversion of Java File class of file paths and git bash.
The solution is to change the paths in the application.properties to a Windows file path with double backslashes - in your case:
/d/Temp/bag/aliases should be changed to D:\\Temp\\bag\\aliases
